### ISSUE TITLE
How to change NPCs velocity? The NPCs are crazy on the map.

### ISSUE THREAD

**Issue by GoroDaimon** [rpgboss/rpgboss#422] opened 2015-10-25 23:40 UTC
Where can I choose the NPCs speed?

**Comment by ravedragon** [comment] 2015-10-26 05:13
npc speed? i assume the walking movement?, that the command call set event speed

**Comment by GoroDaimon** [comment] 2015-10-26 12:40
Thanks!

**Comment by tommycli** [comment] 2015-11-03 15:01
Use "Set Event Speed" event command to change speed.

There's no route support. But you can use "Move Event" command.

**Comment by tommycli** [comment] 2015-11-03 15:04
Oh I understand, the Random movement is crazy.

**Comment by tommycli** [comment] 2015-11-03 15:14
Duplicate of #424

**Closed by tommycli** 2015-11-03 15:14 UTC
Labels: duplicate
